http:
  middlewares:
    server-streaming:
      headers:
        customResponseHeaders:
          X-Accel-Buffering: "no"

  routers:
    server:
      entryPoints:
        - web
      rule: "PathPrefix(`/api`) || PathPrefix(`/auth`) || PathPrefix(`/health`) || PathPrefix(`/metrics`) || PathPrefix(`/swagger`)"
      service: server
      middlewares:
        - server-streaming
      priority: 100
    client:
      entryPoints:
        - web
      rule: "PathPrefix(`/`)"
      service: client
      priority: 1

  services:
    server:
      loadBalancer:
        servers:
          - url: "http://server:8080"
    client:
      loadBalancer:
        servers:
          - url: "http://client:80"
